---
name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-pabot
          pip install webdriver-manager

      - name: Install Browsers & Drivers
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          sudo apt remove --purge firefox
          sudo apt update
          sudo apt install -y firefox
          GECKO_VERSION=$(
            curl -s \
            https://api.github.com/repos/mozilla/geckodriver/releases/latest |
            jq -r '.tag_name' | sed 's/^v//' | xargs
          )
          wget -q \
            "https://github.com/mozilla/geckodriver/releases/download/"\
            "v${GECKO_VERSION}/geckodriver-v${GECKO_VERSION}-linux64.tar.gz" \
            -O geckodriver.tar.gz
          tar -xzf geckodriver.tar.gz
          sudo mv geckodriver /usr/local/bin/

      - name: Debug Repository Files
        run: |
          echo "Current Directory:"
          pwd
          echo "Listing all files and directories:"
          ls -R

      - name: Run Tests in Parallel
        run: |
          source venv/bin/activate
          rm -rf .pabotsuitenames
          pabot --processes 2 tests/test_cases/

      - name: Upload Robot Framework Reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-reports
          path: |
            log.html
            report.html
            output.xml
          retention-days: 7
